import type { StatisticsProvider } from './provider'
import type { StatisticsInterval } from '@/features/statistics/dtoTypes'

const INTERVAL = { from: null, to: null }

const AUTHORS = [
  {
    username: 'anovak',
    fullName: 'Alice Novák',
    institution: 'General Hospital',
    institutionUri: 'http://example.org/institution/1',
    totalRecords: 31,
    completed: 20,
    rejected: 5,
    open: 6,
    totalEvalQ: 248,
    totalInfoQ: 186,
    evaluableAnswers: 221,
    answeredInfo: 164,
    totalCorrectAnswers: 198,
    completionRate: 64.5,
    rejectionRate: 16.1,
    correctnessRate: 89.6,
  },
  {
    username: 'bprochazka',
    fullName: 'Bob Procházka',
    institution: 'General Hospital',
    institutionUri: 'http://example.org/institution/1',
    totalRecords: 27,
    completed: 18,
    rejected: 4,
    open: 5,
    totalEvalQ: 210,
    totalInfoQ: 168,
    evaluableAnswers: 188,
    answeredInfo: 148,
    totalCorrectAnswers: 156,
    completionRate: 66.7,
    rejectionRate: 14.8,
    correctnessRate: 83.0,
  },
  {
    username: 'cdvorak',
    fullName: 'Clara Dvořák',
    institution: 'General Hospital',
    institutionUri: 'http://example.org/institution/1',
    totalRecords: 19,
    completed: 14,
    rejected: 2,
    open: 3,
    totalEvalQ: 152,
    totalInfoQ: 114,
    evaluableAnswers: 141,
    answeredInfo: 103,
    totalCorrectAnswers: 129,
    completionRate: 73.7,
    rejectionRate: 10.5,
    correctnessRate: 91.5,
  },
  {
    username: 'dhoracek',
    fullName: 'David Horáček',
    institution: 'General Hospital',
    institutionUri: 'http://example.org/institution/1',
    totalRecords: 22,
    completed: 13,
    rejected: 6,
    open: 3,
    totalEvalQ: 176,
    totalInfoQ: 132,
    evaluableAnswers: 154,
    answeredInfo: 110,
    totalCorrectAnswers: 101,
    completionRate: 59.1,
    rejectionRate: 27.3,
    correctnessRate: 65.6,
  },
  {
    username: 'esvoboda',
    fullName: 'Elena Svoboda',
    institution: 'General Hospital',
    institutionUri: 'http://example.org/institution/1',
    totalRecords: 35,
    completed: 25,
    rejected: 4,
    open: 6,
    totalEvalQ: 280,
    totalInfoQ: 210,
    evaluableAnswers: 259,
    answeredInfo: 194,
    totalCorrectAnswers: 238,
    completionRate: 71.4,
    rejectionRate: 11.4,
    correctnessRate: 91.9,
  },
  {
    username: 'fblazek',
    fullName: 'Frank Blažek',
    institution: 'General Hospital',
    institutionUri: 'http://example.org/institution/1',
    totalRecords: 14,
    completed: 8,
    rejected: 3,
    open: 3,
    totalEvalQ: 112,
    totalInfoQ: 84,
    evaluableAnswers: 95,
    answeredInfo: 70,
    totalCorrectAnswers: 71,
    completionRate: 57.1,
    rejectionRate: 21.4,
    correctnessRate: 74.7,
  },
  {
    username: 'gkucera',
    fullName: 'Greta Kučera',
    institution: 'General Hospital',
    institutionUri: 'http://example.org/institution/1',
    totalRecords: 28,
    completed: 20,
    rejected: 3,
    open: 5,
    totalEvalQ: 224,
    totalInfoQ: 168,
    evaluableAnswers: 207,
    answeredInfo: 155,
    totalCorrectAnswers: 190,
    completionRate: 71.4,
    rejectionRate: 10.7,
    correctnessRate: 91.8,
  },
  {
    username: 'hjelinek',
    fullName: 'Hans Jelínek',
    institution: 'City Clinic',
    institutionUri: 'http://example.org/institution/2',
    totalRecords: 24,
    completed: 15,
    rejected: 5,
    open: 4,
    totalEvalQ: 192,
    totalInfoQ: 144,
    evaluableAnswers: 168,
    answeredInfo: 122,
    totalCorrectAnswers: 138,
    completionRate: 62.5,
    rejectionRate: 20.8,
    correctnessRate: 82.1,
  },
  {
    username: 'imarkova',
    fullName: 'Irena Marková',
    institution: 'City Clinic',
    institutionUri: 'http://example.org/institution/2',
    totalRecords: 18,
    completed: 12,
    rejected: 2,
    open: 4,
    totalEvalQ: 144,
    totalInfoQ: 108,
    evaluableAnswers: 130,
    answeredInfo: 95,
    totalCorrectAnswers: 114,
    completionRate: 66.7,
    rejectionRate: 11.1,
    correctnessRate: 87.7,
  },
  {
    username: 'jsimanek',
    fullName: 'Jan Šimánek',
    institution: 'City Clinic',
    institutionUri: 'http://example.org/institution/2',
    totalRecords: 33,
    completed: 21,
    rejected: 7,
    open: 5,
    totalEvalQ: 264,
    totalInfoQ: 198,
    evaluableAnswers: 235,
    answeredInfo: 173,
    totalCorrectAnswers: 176,
    completionRate: 63.6,
    rejectionRate: 21.2,
    correctnessRate: 74.9,
  },
  {
    username: 'kvesela',
    fullName: 'Klára Veselá',
    institution: 'City Clinic',
    institutionUri: 'http://example.org/institution/2',
    totalRecords: 21,
    completed: 16,
    rejected: 2,
    open: 3,
    totalEvalQ: 168,
    totalInfoQ: 126,
    evaluableAnswers: 155,
    answeredInfo: 114,
    totalCorrectAnswers: 143,
    completionRate: 76.2,
    rejectionRate: 9.5,
    correctnessRate: 92.3,
  },
  {
    username: 'lpospisil',
    fullName: 'Lukáš Pospíšil',
    institution: 'City Clinic',
    institutionUri: 'http://example.org/institution/2',
    totalRecords: 16,
    completed: 9,
    rejected: 4,
    open: 3,
    totalEvalQ: 128,
    totalInfoQ: 96,
    evaluableAnswers: 109,
    answeredInfo: 80,
    totalCorrectAnswers: 76,
    completionRate: 56.3,
    rejectionRate: 25.0,
    correctnessRate: 69.7,
  },
  {
    username: 'mnovakova',
    fullName: 'Marta Nováková',
    institution: 'City Clinic',
    institutionUri: 'http://example.org/institution/2',
    totalRecords: 29,
    completed: 20,
    rejected: 4,
    open: 5,
    totalEvalQ: 232,
    totalInfoQ: 174,
    evaluableAnswers: 213,
    answeredInfo: 158,
    totalCorrectAnswers: 195,
    completionRate: 69.0,
    rejectionRate: 13.8,
    correctnessRate: 91.5,
  },
  {
    username: 'nbenes',
    fullName: 'Norbert Beneš',
    institution: 'University Medical Center',
    institutionUri: 'http://example.org/institution/3',
    totalRecords: 26,
    completed: 18,
    rejected: 4,
    open: 4,
    totalEvalQ: 208,
    totalInfoQ: 156,
    evaluableAnswers: 190,
    answeredInfo: 140,
    totalCorrectAnswers: 174,
    completionRate: 69.2,
    rejectionRate: 15.4,
    correctnessRate: 91.6,
  },
  {
    username: 'ocervena',
    fullName: 'Olga Červená',
    institution: 'University Medical Center',
    institutionUri: 'http://example.org/institution/3',
    totalRecords: 20,
    completed: 15,
    rejected: 2,
    open: 3,
    totalEvalQ: 160,
    totalInfoQ: 120,
    evaluableAnswers: 148,
    answeredInfo: 109,
    totalCorrectAnswers: 137,
    completionRate: 75.0,
    rejectionRate: 10.0,
    correctnessRate: 92.6,
  },
  {
    username: 'pkratochvil',
    fullName: 'Pavel Kratochvíl',
    institution: 'University Medical Center',
    institutionUri: 'http://example.org/institution/3',
    totalRecords: 23,
    completed: 14,
    rejected: 5,
    open: 4,
    totalEvalQ: 184,
    totalInfoQ: 138,
    evaluableAnswers: 161,
    answeredInfo: 118,
    totalCorrectAnswers: 130,
    completionRate: 60.9,
    rejectionRate: 21.7,
    correctnessRate: 80.7,
  },
  {
    username: 'rkopecka',
    fullName: 'Renata Kopecká',
    institution: 'University Medical Center',
    institutionUri: 'http://example.org/institution/3',
    totalRecords: 17,
    completed: 12,
    rejected: 2,
    open: 3,
    totalEvalQ: 136,
    totalInfoQ: 102,
    evaluableAnswers: 124,
    answeredInfo: 92,
    totalCorrectAnswers: 115,
    completionRate: 70.6,
    rejectionRate: 11.8,
    correctnessRate: 92.7,
  },
  {
    username: 'svlcek',
    fullName: 'Stanislav Vlček',
    institution: 'University Medical Center',
    institutionUri: 'http://example.org/institution/3',
    totalRecords: 30,
    completed: 19,
    rejected: 6,
    open: 5,
    totalEvalQ: 240,
    totalInfoQ: 180,
    evaluableAnswers: 214,
    answeredInfo: 158,
    totalCorrectAnswers: 171,
    completionRate: 63.3,
    rejectionRate: 20.0,
    correctnessRate: 79.9,
  },
  {
    username: 'tblazkova',
    fullName: 'Tereza Blažková',
    institution: 'Regional Health Institute',
    institutionUri: 'http://example.org/institution/4',
    totalRecords: 15,
    completed: 8,
    rejected: 4,
    open: 3,
    totalEvalQ: 120,
    totalInfoQ: 90,
    evaluableAnswers: 101,
    answeredInfo: 74,
    totalCorrectAnswers: 72,
    completionRate: 53.3,
    rejectionRate: 26.7,
    correctnessRate: 71.3,
  },
  {
    username: 'umarek',
    fullName: 'Uwe Marek',
    institution: 'Regional Health Institute',
    institutionUri: 'http://example.org/institution/4',
    totalRecords: 12,
    completed: 7,
    rejected: 3,
    open: 2,
    totalEvalQ: 96,
    totalInfoQ: 72,
    evaluableAnswers: 83,
    answeredInfo: 61,
    totalCorrectAnswers: 60,
    completionRate: 58.3,
    rejectionRate: 25.0,
    correctnessRate: 72.3,
  },
  {
    username: 'vzemanova',
    fullName: 'Věra Zemanová',
    institution: 'Regional Health Institute',
    institutionUri: 'http://example.org/institution/4',
    totalRecords: 19,
    completed: 11,
    rejected: 4,
    open: 4,
    totalEvalQ: 152,
    totalInfoQ: 114,
    evaluableAnswers: 133,
    answeredInfo: 98,
    totalCorrectAnswers: 105,
    completionRate: 57.9,
    rejectionRate: 21.1,
    correctnessRate: 78.9,
  },
  {
    username: 'wshedy',
    fullName: 'Waldemar Šedý',
    institution: 'Regional Health Institute',
    institutionUri: 'http://example.org/institution/4',
    totalRecords: 10,
    completed: 5,
    rejected: 3,
    open: 2,
    totalEvalQ: 80,
    totalInfoQ: 60,
    evaluableAnswers: 66,
    answeredInfo: 48,
    totalCorrectAnswers: 45,
    completionRate: 50.0,
    rejectionRate: 30.0,
    correctnessRate: 68.2,
  },
  {
    username: 'xbartosova',
    fullName: 'Xenie Bartošová',
    institution: 'Regional Health Institute',
    institutionUri: 'http://example.org/institution/4',
    totalRecords: 13,
    completed: 8,
    rejected: 2,
    open: 3,
    totalEvalQ: 104,
    totalInfoQ: 78,
    evaluableAnswers: 91,
    answeredInfo: 67,
    totalCorrectAnswers: 78,
    completionRate: 61.5,
    rejectionRate: 15.4,
    correctnessRate: 85.7,
  },
  {
    username: 'ydusek',
    fullName: 'Yvonne Dušek',
    institution: 'Regional Health Institute',
    institutionUri: 'http://example.org/institution/4',
    totalRecords: 11,
    completed: 6,
    rejected: 3,
    open: 2,
    totalEvalQ: 88,
    totalInfoQ: 66,
    evaluableAnswers: 74,
    answeredInfo: 54,
    totalCorrectAnswers: 55,
    completionRate: 54.5,
    rejectionRate: 27.3,
    correctnessRate: 74.3,
  },
  {
    username: 'zfiala',
    fullName: 'Zdeněk Fiala',
    institution: 'Regional Health Institute',
    institutionUri: 'http://example.org/institution/4',
    totalRecords: 8,
    completed: 4,
    rejected: 2,
    open: 2,
    totalEvalQ: 64,
    totalInfoQ: 48,
    evaluableAnswers: 53,
    answeredInfo: 39,
    totalCorrectAnswers: 38,
    completionRate: 50.0,
    rejectionRate: 25.0,
    correctnessRate: 71.7,
  },
]

const MOCK_AUTHORS = AUTHORS.map((a) => ({
  label: 'Authors across the system' as const,
  description: null,
  interval: INTERVAL,
  username: a.username,
  fullName: a.fullName,
  totalRecords: a.totalRecords,
  completionRate: a.completionRate,
  rejectionRate: a.rejectionRate,
  totalAnswers: a.evaluableAnswers + a.answeredInfo,
  evaluableAnswers: a.evaluableAnswers,
  totalCorrectAnswers: a.totalCorrectAnswers,
  correctnessRate: a.correctnessRate,
  totalEvaluableQuestions: a.totalEvalQ,
  totalInformativeQuestions: a.totalInfoQ,
  byPhase: { open: a.open, completed: a.completed, rejected: a.rejected },
  periodFrom: '2024-01-01T00:00:00Z',
  periodTo: '2024-12-31T23:59:59Z',
  institutionName: a.institution,
  institutionUri: a.institutionUri,
}))

const MOCK_OVERVIEW = {
  label: 'Authors across the system' as const,
  description: null,
  interval: INTERVAL,
  totalAuthors: MOCK_AUTHORS.length,
  mostRecordsAuthorInfo: 'Elena Svoboda – 35 records',
  mostAnswersAuthorInfo: 'Elena Svoboda – 453 answers',
  bestCompletionRateInfo: 'Klára Veselá – 76.2%',
  mostRejectionRateInfo: 'Waldemar Šedý – 30.0%',
  bestAnswerCorrectnessInfo: 'Renata Kopecká – 92.7%',
}

const INSTITUTION_RECORDS = [
  {
    uri: 'http://example.org/record/r001',
    name: 'Novák Jan – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    totalQuestions: 20,
    totalAnswers: 20,
    totalEvaluableAnswers: 16,
    totalCorrectAnswers: 14,
    correctnessRate: 87.5,
    certification: { label: 'Certified – Level A', description: null },
    dateCreated: '2024-01-12T08:30:00Z',
    authorFullName: 'Alice Novák',
    authorUsername: 'anovak',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r002',
    name: 'Svoboda Petr – propuštění',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Discharge form',
    totalQuestions: 15,
    totalAnswers: 15,
    totalEvaluableAnswers: 13,
    totalCorrectAnswers: 12,
    correctnessRate: 92.3,
    certification: { label: 'Certified – Level A', description: null },
    dateCreated: '2024-01-18T10:15:00Z',
    authorFullName: 'Bob Procházka',
    authorUsername: 'bprochazka',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r003',
    name: null,
    phase: 'OPEN' as const,
    formTemplateLabel: 'Admission form',
    totalQuestions: 20,
    totalAnswers: 11,
    totalEvaluableAnswers: 0,
    totalCorrectAnswers: 0,
    correctnessRate: 0,
    certification: null,
    dateCreated: '2024-01-25T14:00:00Z',
    authorFullName: 'Clara Dvořák',
    authorUsername: 'cdvorak',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r004',
    name: 'Horáček Jiří – kontrola',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Follow-up form',
    totalQuestions: 10,
    totalAnswers: 10,
    totalEvaluableAnswers: 8,
    totalCorrectAnswers: 5,
    correctnessRate: 62.5,
    certification: null,
    dateCreated: '2024-02-03T09:45:00Z',
    authorFullName: 'David Horáček',
    authorUsername: 'dhoracek',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r005',
    name: 'Procházková Eva – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    totalQuestions: 20,
    totalAnswers: 20,
    totalEvaluableAnswers: 17,
    totalCorrectAnswers: 16,
    correctnessRate: 94.1,
    certification: { label: 'Certified – Level B', description: null },
    dateCreated: '2024-02-10T11:20:00Z',
    authorFullName: 'Elena Svoboda',
    authorUsername: 'esvoboda',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r006',
    name: null,
    phase: 'REJECTED' as const,
    formTemplateLabel: 'Emergency form',
    totalQuestions: 12,
    totalAnswers: 12,
    totalEvaluableAnswers: 10,
    totalCorrectAnswers: 6,
    correctnessRate: 60.0,
    certification: null,
    dateCreated: '2024-02-14T16:30:00Z',
    authorFullName: 'Frank Blažek',
    authorUsername: 'fblazek',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r007',
    name: 'Nováková Lucie – propuštění',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Discharge form',
    totalQuestions: 15,
    totalAnswers: 15,
    totalEvaluableAnswers: 12,
    totalCorrectAnswers: 11,
    correctnessRate: 91.7,
    certification: { label: 'Certified – Level A', description: null },
    dateCreated: '2024-02-22T08:00:00Z',
    authorFullName: 'Greta Kučera',
    authorUsername: 'gkucera',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r008',
    name: null,
    phase: 'OPEN' as const,
    formTemplateLabel: 'Follow-up form',
    totalQuestions: 10,
    totalAnswers: 4,
    totalEvaluableAnswers: 0,
    totalCorrectAnswers: 0,
    correctnessRate: 0,
    certification: null,
    dateCreated: '2024-03-01T13:10:00Z',
    authorFullName: 'Alice Novák',
    authorUsername: 'anovak',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r009',
    name: 'Blažek Tomáš – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    totalQuestions: 20,
    totalAnswers: 19,
    totalEvaluableAnswers: 15,
    totalCorrectAnswers: 13,
    correctnessRate: 86.7,
    certification: { label: 'Certified – Level A', description: null },
    dateCreated: '2024-03-08T09:30:00Z',
    authorFullName: 'Elena Svoboda',
    authorUsername: 'esvoboda',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r010',
    name: null,
    phase: 'REJECTED' as const,
    formTemplateLabel: 'Admission form',
    totalQuestions: 20,
    totalAnswers: 14,
    totalEvaluableAnswers: 11,
    totalCorrectAnswers: 4,
    correctnessRate: 36.4,
    certification: null,
    dateCreated: '2024-03-15T15:45:00Z',
    authorFullName: 'David Horáček',
    authorUsername: 'dhoracek',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r011',
    name: 'Veselá Jana – kontrola',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Follow-up form',
    totalQuestions: 10,
    totalAnswers: 10,
    totalEvaluableAnswers: 9,
    totalCorrectAnswers: 9,
    correctnessRate: 100.0,
    certification: { label: 'Certified – Level B', description: null },
    dateCreated: '2024-03-22T10:00:00Z',
    authorFullName: 'Greta Kučera',
    authorUsername: 'gkucera',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r012',
    name: 'Kratochvíl Karel – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    totalQuestions: 20,
    totalAnswers: 20,
    totalEvaluableAnswers: 16,
    totalCorrectAnswers: 15,
    correctnessRate: 93.8,
    certification: { label: 'Certified – Level A', description: null },
    dateCreated: '2024-04-02T08:15:00Z',
    authorFullName: 'Clara Dvořák',
    authorUsername: 'cdvorak',
    institutionName: 'General Hospital',
  },
]

const ALL_RECORDS = [
  ...INSTITUTION_RECORDS,
  {
    uri: 'http://example.org/record/r013',
    name: 'Jelínek Radek – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    totalQuestions: 20,
    totalAnswers: 20,
    totalEvaluableAnswers: 16,
    totalCorrectAnswers: 15,
    correctnessRate: 93.8,
    certification: { label: 'Certified – Level A', description: null },
    dateCreated: '2024-01-15T09:00:00Z',
    authorFullName: 'Hans Jelínek',
    authorUsername: 'hjelinek',
    institutionName: 'City Clinic',
  },
  {
    uri: 'http://example.org/record/r014',
    name: null,
    phase: 'OPEN' as const,
    formTemplateLabel: 'Follow-up form',
    totalQuestions: 10,
    totalAnswers: 6,
    totalEvaluableAnswers: 0,
    totalCorrectAnswers: 0,
    correctnessRate: 0,
    certification: null,
    dateCreated: '2024-02-05T11:30:00Z',
    authorFullName: 'Irena Marková',
    authorUsername: 'imarkova',
    institutionName: 'City Clinic',
  },
  {
    uri: 'http://example.org/record/r015',
    name: 'Šimánek Ondřej – propuštění',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Discharge form',
    totalQuestions: 15,
    totalAnswers: 15,
    totalEvaluableAnswers: 13,
    totalCorrectAnswers: 10,
    correctnessRate: 76.9,
    certification: null,
    dateCreated: '2024-02-19T14:20:00Z',
    authorFullName: 'Jan Šimánek',
    authorUsername: 'jsimanek',
    institutionName: 'City Clinic',
  },
  {
    uri: 'http://example.org/record/r016',
    name: 'Veselá Monika – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    totalQuestions: 20,
    totalAnswers: 20,
    totalEvaluableAnswers: 17,
    totalCorrectAnswers: 16,
    correctnessRate: 94.1,
    certification: { label: 'Certified – Level B', description: null },
    dateCreated: '2024-03-04T08:45:00Z',
    authorFullName: 'Klára Veselá',
    authorUsername: 'kvesela',
    institutionName: 'City Clinic',
  },
  {
    uri: 'http://example.org/record/r017',
    name: null,
    phase: 'REJECTED' as const,
    formTemplateLabel: 'Emergency form',
    totalQuestions: 12,
    totalAnswers: 12,
    totalEvaluableAnswers: 10,
    totalCorrectAnswers: 5,
    correctnessRate: 50.0,
    certification: null,
    dateCreated: '2024-03-18T17:00:00Z',
    authorFullName: 'Lukáš Pospíšil',
    authorUsername: 'lpospisil',
    institutionName: 'City Clinic',
  },
  {
    uri: 'http://example.org/record/r018',
    name: 'Nováková Alžběta – kontrola',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Follow-up form',
    totalQuestions: 10,
    totalAnswers: 10,
    totalEvaluableAnswers: 9,
    totalCorrectAnswers: 8,
    correctnessRate: 88.9,
    certification: { label: 'Certified – Level A', description: null },
    dateCreated: '2024-04-01T10:30:00Z',
    authorFullName: 'Marta Nováková',
    authorUsername: 'mnovakova',
    institutionName: 'City Clinic',
  },
  {
    uri: 'http://example.org/record/r019',
    name: 'Beneš Miroslav – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    totalQuestions: 20,
    totalAnswers: 19,
    totalEvaluableAnswers: 15,
    totalCorrectAnswers: 14,
    correctnessRate: 93.3,
    certification: { label: 'Certified – Level A', description: null },
    dateCreated: '2024-01-22T09:15:00Z',
    authorFullName: 'Norbert Beneš',
    authorUsername: 'nbenes',
    institutionName: 'University Medical Center',
  },
  {
    uri: 'http://example.org/record/r020',
    name: null,
    phase: 'OPEN' as const,
    formTemplateLabel: 'Admission form',
    totalQuestions: 20,
    totalAnswers: 8,
    totalEvaluableAnswers: 0,
    totalCorrectAnswers: 0,
    correctnessRate: 0,
    certification: null,
    dateCreated: '2024-02-08T13:00:00Z',
    authorFullName: 'Olga Červená',
    authorUsername: 'ocervena',
    institutionName: 'University Medical Center',
  },
  {
    uri: 'http://example.org/record/r021',
    name: 'Kratochvíl Zdeněk – propuštění',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Discharge form',
    totalQuestions: 15,
    totalAnswers: 15,
    totalEvaluableAnswers: 12,
    totalCorrectAnswers: 9,
    correctnessRate: 75.0,
    certification: null,
    dateCreated: '2024-02-26T11:45:00Z',
    authorFullName: 'Pavel Kratochvíl',
    authorUsername: 'pkratochvil',
    institutionName: 'University Medical Center',
  },
  {
    uri: 'http://example.org/record/r022',
    name: 'Kopecká Renata – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    totalQuestions: 20,
    totalAnswers: 20,
    totalEvaluableAnswers: 17,
    totalCorrectAnswers: 16,
    correctnessRate: 94.1,
    certification: { label: 'Certified – Level B', description: null },
    dateCreated: '2024-03-12T08:00:00Z',
    authorFullName: 'Renata Kopecká',
    authorUsername: 'rkopecka',
    institutionName: 'University Medical Center',
  },
  {
    uri: 'http://example.org/record/r023',
    name: null,
    phase: 'REJECTED' as const,
    formTemplateLabel: 'Emergency form',
    totalQuestions: 12,
    totalAnswers: 11,
    totalEvaluableAnswers: 9,
    totalCorrectAnswers: 4,
    correctnessRate: 44.4,
    certification: null,
    dateCreated: '2024-03-28T16:20:00Z',
    authorFullName: 'Stanislav Vlček',
    authorUsername: 'svlcek',
    institutionName: 'University Medical Center',
  },
  {
    uri: 'http://example.org/record/r024',
    name: 'Blažková Jana – kontrola',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Follow-up form',
    totalQuestions: 10,
    totalAnswers: 10,
    totalEvaluableAnswers: 8,
    totalCorrectAnswers: 6,
    correctnessRate: 75.0,
    certification: null,
    dateCreated: '2024-01-30T10:00:00Z',
    authorFullName: 'Tereza Blažková',
    authorUsername: 'tblazkova',
    institutionName: 'Regional Health Institute',
  },
  {
    uri: 'http://example.org/record/r025',
    name: null,
    phase: 'OPEN' as const,
    formTemplateLabel: 'Admission form',
    totalQuestions: 20,
    totalAnswers: 7,
    totalEvaluableAnswers: 0,
    totalCorrectAnswers: 0,
    correctnessRate: 0,
    certification: null,
    dateCreated: '2024-02-15T14:30:00Z',
    authorFullName: 'Uwe Marek',
    authorUsername: 'umarek',
    institutionName: 'Regional Health Institute',
  },
  {
    uri: 'http://example.org/record/r026',
    name: 'Zemanová Věra – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    totalQuestions: 20,
    totalAnswers: 18,
    totalEvaluableAnswers: 14,
    totalCorrectAnswers: 11,
    correctnessRate: 78.6,
    certification: { label: 'Certified – Level A', description: null },
    dateCreated: '2024-03-05T09:30:00Z',
    authorFullName: 'Věra Zemanová',
    authorUsername: 'vzemanova',
    institutionName: 'Regional Health Institute',
  },
  {
    uri: 'http://example.org/record/r027',
    name: null,
    phase: 'REJECTED' as const,
    formTemplateLabel: 'Discharge form',
    totalQuestions: 15,
    totalAnswers: 15,
    totalEvaluableAnswers: 12,
    totalCorrectAnswers: 5,
    correctnessRate: 41.7,
    certification: null,
    dateCreated: '2024-03-20T15:00:00Z',
    authorFullName: 'Waldemar Šedý',
    authorUsername: 'wshedy',
    institutionName: 'Regional Health Institute',
  },
  {
    uri: 'http://example.org/record/r028',
    name: 'Bartošová Zuzana – kontrola',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Follow-up form',
    totalQuestions: 10,
    totalAnswers: 10,
    totalEvaluableAnswers: 9,
    totalCorrectAnswers: 8,
    correctnessRate: 88.9,
    certification: { label: 'Certified – Level A', description: null },
    dateCreated: '2024-04-05T11:00:00Z',
    authorFullName: 'Xenie Bartošová',
    authorUsername: 'xbartosova',
    institutionName: 'Regional Health Institute',
  },
]

const toRecordBase = (r: (typeof ALL_RECORDS)[number]) => ({
  uri: r.uri,
  name: r.name,
  phase: r.phase,
  formTemplateLabel: r.formTemplateLabel,
  totalQuestions: r.totalQuestions,
  totalAnswers: r.totalAnswers,
  totalEvaluableAnswers: r.totalEvaluableAnswers,
  totalCorrectAnswers: r.totalCorrectAnswers,
  correctnessRate: r.correctnessRate,
  certification: r.certification,
  dateCreated: r.dateCreated,
})

export const mockStatisticsProvider: StatisticsProvider = {
  async getAllAuthorsOverview(_interval: StatisticsInterval) {
    return { ...MOCK_OVERVIEW, label: 'Authors across the system' as const }
  },

  async getAllAuthors(_interval: StatisticsInterval, _username?: string) {
    return {
      label: 'Authors across the system' as const,
      description: null,
      interval: INTERVAL,
      authors: MOCK_AUTHORS,
      overview: MOCK_OVERVIEW,
    }
  },

  async getInstitutionAuthorsOverview(_interval: StatisticsInterval) {
    return { ...MOCK_OVERVIEW, label: 'Authors in your institution' as const }
  },

  async getInstitutionAuthors(_interval: StatisticsInterval, _username?: string) {
    const institutionAuthors = MOCK_AUTHORS.filter((a) => a.institutionName === 'General Hospital')
    return {
      label: 'Authors in your institution' as const,
      description: null,
      interval: INTERVAL,
      authors: institutionAuthors,
      overview: {
        ...MOCK_OVERVIEW,
        label: 'Authors in your institution' as const,
        totalAuthors: institutionAuthors.length,
      },
    }
  },

  async getAuthorByUsername(username: string, _interval: StatisticsInterval) {
    return {
      label: 'Personal statistics' as const,
      description: null,
      interval: INTERVAL,
      username,
      fullName: 'Demo User',
      totalRecords: 38,
      completionRate: 65.8,
      rejectionRate: 13.2,
      totalAnswers: 532,
      evaluableAnswers: 418,
      totalCorrectAnswers: 374,
      correctnessRate: 89.5,
      byPhase: { open: 8, completed: 25, rejected: 5 },
      periodFrom: '2024-02-01T00:00:00Z',
      periodTo: '2024-11-30T23:59:59Z',
      institutionName: 'General Hospital',
      institutionUri: 'http://example.org/institution/1',
    }
  },

  async getPersonalRecords(_interval: StatisticsInterval) {
    return {
      label: 'My records' as const,
      description: 'Records created within the selected period. Click a record to view details.',
      interval: INTERVAL,
      total: 12,
      records: [
        {
          uri: 'http://example.org/record/af3d9',
          name: 'Jan Novák intake',
          phase: 'COMPLETED' as const,
          formTemplateLabel: 'Admission form',
          totalQuestions: 20,
          totalAnswers: 20,
          totalEvaluableAnswers: 16,
          totalCorrectAnswers: 14,
          correctnessRate: 87.5,
          certification: {
            label: 'Certified – Level A',
            description: 'Passed all mandatory criteria.',
          },
          dateCreated: '2024-02-08T09:14:00Z',
        },
        {
          uri: 'http://example.org/record/d554a',
          name: 'Svoboda follow-up',
          phase: 'COMPLETED' as const,
          formTemplateLabel: 'Follow-up form',
          totalQuestions: 10,
          totalAnswers: 10,
          totalEvaluableAnswers: 8,
          totalCorrectAnswers: 8,
          correctnessRate: 100.0,
          certification: { label: 'Certified – Level B', description: null },
          dateCreated: '2024-04-18T14:30:00Z',
        },
        {
          uri: 'http://example.org/record/k890h',
          name: 'Horáček discharge',
          phase: 'COMPLETED' as const,
          formTemplateLabel: 'Discharge form',
          totalQuestions: 15,
          totalAnswers: 15,
          totalEvaluableAnswers: 14,
          totalCorrectAnswers: 13,
          correctnessRate: 92.9,
          certification: { label: 'Certified – Level A', description: '' },
          dateCreated: '2024-10-05T11:50:00Z',
        },
        {
          uri: 'http://example.org/record/b12cc',
          name: 'Novák discharge',
          phase: 'COMPLETED' as const,
          formTemplateLabel: 'Discharge form',
          totalQuestions: 15,
          totalAnswers: 15,
          totalEvaluableAnswers: 12,
          totalCorrectAnswers: 11,
          correctnessRate: 91.7,
          certification: null,
          dateCreated: '2024-03-15T11:02:00Z',
        },
        {
          uri: 'http://example.org/record/f230d',
          name: 'Procházka discharge',
          phase: 'COMPLETED' as const,
          formTemplateLabel: 'Discharge form',
          totalQuestions: 15,
          totalAnswers: 15,
          totalEvaluableAnswers: 13,
          totalCorrectAnswers: 12,
          correctnessRate: 92.3,
          certification: null,
          dateCreated: '2024-05-27T16:10:00Z',
        },
        {
          uri: 'http://example.org/record/c887e',
          name: null,
          phase: 'REJECTED' as const,
          formTemplateLabel: 'Admission form',
          totalQuestions: 20,
          totalAnswers: 14,
          totalEvaluableAnswers: 10,
          totalCorrectAnswers: 6,
          correctnessRate: 60.0,
          certification: null,
          dateCreated: '2024-04-01T08:45:00Z',
        },
        {
          uri: 'http://example.org/record/j321g',
          name: null,
          phase: 'REJECTED' as const,
          formTemplateLabel: 'Emergency form',
          totalQuestions: 12,
          totalAnswers: 12,
          totalEvaluableAnswers: 11,
          totalCorrectAnswers: 7,
          correctnessRate: 63.6,
          certification: null,
          dateCreated: '2024-09-11T15:25:00Z',
        },
        {
          uri: 'http://example.org/record/e991b',
          name: null,
          phase: 'OPEN' as const,
          formTemplateLabel: 'Admission form',
          totalQuestions: 20,
          totalAnswers: 9,
          totalEvaluableAnswers: 0,
          totalCorrectAnswers: 0,
          correctnessRate: 0,
          certification: null,
          dateCreated: '2024-05-03T10:20:00Z',
        },
        {
          uri: 'http://example.org/record/h102c',
          name: 'Dvořák check-in',
          phase: 'OPEN' as const,
          formTemplateLabel: 'Follow-up form',
          totalQuestions: 10,
          totalAnswers: 4,
          totalEvaluableAnswers: 0,
          totalCorrectAnswers: 0,
          correctnessRate: 0,
          certification: null,
          dateCreated: '2024-07-09T13:40:00Z',
        },
        {
          uri: 'http://example.org/record/l567i',
          name: null,
          phase: 'OPEN' as const,
          formTemplateLabel: 'Admission form',
          totalQuestions: 20,
          totalAnswers: 6,
          totalEvaluableAnswers: 0,
          totalCorrectAnswers: 0,
          correctnessRate: 0,
          certification: null,
          dateCreated: '2024-11-18T08:30:00Z',
        },
        {
          uri: 'http://example.org/record/g774f',
          name: null,
          phase: 'COMPLETED' as const,
          formTemplateLabel: 'Emergency form',
          totalQuestions: 12,
          totalAnswers: 12,
          totalEvaluableAnswers: 10,
          totalCorrectAnswers: 9,
          correctnessRate: 90.0,
          certification: null,
          dateCreated: '2024-06-14T07:55:00Z',
        },
        {
          uri: 'http://example.org/record/i456e',
          name: null,
          phase: 'COMPLETED' as const,
          formTemplateLabel: 'Admission form',
          totalQuestions: 20,
          totalAnswers: 20,
          totalEvaluableAnswers: 17,
          totalCorrectAnswers: 15,
          correctnessRate: 88.2,
          certification: null,
          dateCreated: '2024-08-22T09:00:00Z',
        },
      ],
      phaseDistribution: {
        interval: INTERVAL,
        total: 12,
        distribution: [
          { phase: 'OPEN' as const, count: 3, percentage: 25.0 },
          { phase: 'COMPLETED' as const, count: 7, percentage: 58.3 },
          { phase: 'REJECTED' as const, count: 2, percentage: 16.7 },
        ],
      },
      formTemplateUsage: {
        label: 'My records' as const,
        description: null,
        interval: INTERVAL,
        total: 12,
        templates: [
          {
            templateUri: 'http://example.org/form/admission',
            templateLabel: 'Admission form',
            count: 5,
            percentage: 41.7,
          },
          {
            templateUri: 'http://example.org/form/discharge',
            templateLabel: 'Discharge form',
            count: 3,
            percentage: 25.0,
          },
          {
            templateUri: 'http://example.org/form/followup',
            templateLabel: 'Follow-up form',
            count: 2,
            percentage: 16.7,
          },
          {
            templateUri: 'http://example.org/form/emergency',
            templateLabel: 'Emergency form',
            count: 2,
            percentage: 16.7,
          },
        ],
      },
    }
  },

  async getInstitutionRecords(_interval: StatisticsInterval) {
    const records = INSTITUTION_RECORDS.map((r) => ({
      ...toRecordBase(r),
      institutionName: r.institutionName,
      authorUsername: r.authorUsername,
    }))
    return {
      label: 'Records in your institution' as const,
      description: null,
      interval: INTERVAL,
      total: records.length,
      records,
      phaseDistribution: {
        interval: INTERVAL,
        total: records.length,
        distribution: [
          { phase: 'OPEN' as const, count: 2, percentage: 16.7 },
          { phase: 'COMPLETED' as const, count: 8, percentage: 66.7 },
          { phase: 'REJECTED' as const, count: 2, percentage: 16.7 },
        ],
      },
      formTemplateUsage: {
        label: 'Records in your institution' as const,
        description: null,
        interval: INTERVAL,
        total: records.length,
        templates: [
          {
            templateUri: 'http://example.org/form/admission',
            templateLabel: 'Admission form',
            count: 5,
            percentage: 41.7,
          },
          {
            templateUri: 'http://example.org/form/discharge',
            templateLabel: 'Discharge form',
            count: 3,
            percentage: 25.0,
          },
          {
            templateUri: 'http://example.org/form/followup',
            templateLabel: 'Follow-up form',
            count: 3,
            percentage: 25.0,
          },
          {
            templateUri: 'http://example.org/form/emergency',
            templateLabel: 'Emergency form',
            count: 1,
            percentage: 8.3,
          },
        ],
      },
    }
  },

  async getAllRecords(_interval: StatisticsInterval) {
    const records = ALL_RECORDS.map((r) => ({
      ...toRecordBase(r),
      institutionName: r.institutionName,
      authorFullName: r.authorFullName,
      authorUsername: r.authorUsername,
    }))
    return {
      label: 'All records in the system' as const,
      description: null,
      interval: INTERVAL,
      total: records.length,
      records,
      phaseDistribution: {
        interval: INTERVAL,
        total: records.length,
        distribution: [
          { phase: 'OPEN' as const, count: 6, percentage: 21.4 },
          { phase: 'COMPLETED' as const, count: 18, percentage: 64.3 },
          { phase: 'REJECTED' as const, count: 4, percentage: 14.3 },
        ],
      },
      formTemplateUsage: {
        label: 'All records in the system' as const,
        description: null,
        interval: INTERVAL,
        total: records.length,
        templates: [
          {
            templateUri: 'http://example.org/form/admission',
            templateLabel: 'Admission form',
            count: 12,
            percentage: 42.9,
          },
          {
            templateUri: 'http://example.org/form/discharge',
            templateLabel: 'Discharge form',
            count: 6,
            percentage: 21.4,
          },
          {
            templateUri: 'http://example.org/form/followup',
            templateLabel: 'Follow-up form',
            count: 6,
            percentage: 21.4,
          },
          {
            templateUri: 'http://example.org/form/emergency',
            templateLabel: 'Emergency form',
            count: 4,
            percentage: 14.3,
          },
        ],
      },
    }
  },

  async getAllInstitutions(_interval: StatisticsInterval) {
    return {
      label: 'Institutions across the system' as const,
      description: null,
      interval: INTERVAL,
      totalInstitutions: 4,
      mostRecordsInstitutionInfo: 'General Hospital – 89 records',
      mostAnswersInstitutionInfo: 'General Hospital – 1 240 answers',
      bestCompletionRateInstitutionInfo: 'General Hospital – 68.5%',
      mostRejectionRateInstitutionInfo: 'Regional Health Institute – 18.8%',
      bestAnswerCorrectnessInstitutionInfo: 'University Medical Center – 91.3%',
      institutions: [
        {
          uri: 'http://example.org/institution/1',
          name: 'General Hospital',
          totalRecords: 89,
          authorCount: 7,
          completionRate: 68.5,
          rejectionRate: 11.2,
          totalAnswers: 1240,
          evaluableAnswers: 980,
          totalCorrectAnswers: 893,
          correctnessRate: 91.1,
        },
        {
          uri: 'http://example.org/institution/2',
          name: 'City Clinic',
          totalRecords: 72,
          authorCount: 6,
          completionRate: 58.3,
          rejectionRate: 16.7,
          totalAnswers: 960,
          evaluableAnswers: 820,
          totalCorrectAnswers: 714,
          correctnessRate: 87.1,
        },
        {
          uri: 'http://example.org/institution/3',
          name: 'University Medical Center',
          totalRecords: 54,
          authorCount: 5,
          completionRate: 64.8,
          rejectionRate: 13.0,
          totalAnswers: 750,
          evaluableAnswers: 640,
          totalCorrectAnswers: 584,
          correctnessRate: 91.3,
        },
        {
          uri: 'http://example.org/institution/4',
          name: 'Regional Health Institute',
          totalRecords: 32,
          authorCount: 5,
          completionRate: 53.1,
          rejectionRate: 18.8,
          totalAnswers: 430,
          evaluableAnswers: 380,
          totalCorrectAnswers: 318,
          correctnessRate: 83.7,
        },
      ],
    }
  },

  async getPermissions() {
    return {
      canReadAllRecords: true,
      canReadOrgRecords: true,
      canReadAllUsers: true,
      canReadOrgUsers: true,
      canReadAllOrganizations: true,
      canReadOrganization: true,
      canReadStatistics: true,
    }
  },
}
