import type { StatisticsProvider } from './provider'
import type { RecordPhase, StatisticsInterval } from '@/shared/dto/statistics.dto'

const INTERVAL = { from: null, to: null }

const AUTHORS = [
  {
    username: 'anovak',
    fullName: 'Alice Novák',
    institution: 'General Hospital',
    institutionUri: 'http://example.org/institution/1',
    totalRecords: 31,
    completed: 20,
    rejected: 5,
    open: 6,
    qEval: 248,
    qInfo: 186,
    aEval: 221,
    aInfo: 164,
    correct: 198,
    completionRate: 64.5,
    rejectionRate: 16.1,
  },
  {
    username: 'bprochazka',
    fullName: 'Bob Procházka',
    institution: 'General Hospital',
    institutionUri: 'http://example.org/institution/1',
    totalRecords: 27,
    completed: 18,
    rejected: 4,
    open: 5,
    qEval: 210,
    qInfo: 168,
    aEval: 188,
    aInfo: 148,
    correct: 156,
    completionRate: 66.7,
    rejectionRate: 14.8,
  },
  {
    username: 'cdvorak',
    fullName: 'Clara Dvořák',
    institution: 'General Hospital',
    institutionUri: 'http://example.org/institution/1',
    totalRecords: 19,
    completed: 14,
    rejected: 2,
    open: 3,
    qEval: 152,
    qInfo: 114,
    aEval: 141,
    aInfo: 103,
    correct: 129,
    completionRate: 73.7,
    rejectionRate: 10.5,
  },
  {
    username: 'dhoracek',
    fullName: 'David Horáček',
    institution: 'General Hospital',
    institutionUri: 'http://example.org/institution/1',
    totalRecords: 22,
    completed: 13,
    rejected: 6,
    open: 3,
    qEval: 176,
    qInfo: 132,
    aEval: 154,
    aInfo: 110,
    correct: 101,
    completionRate: 59.1,
    rejectionRate: 27.3,
  },
  {
    username: 'esvoboda',
    fullName: 'Elena Svoboda',
    institution: 'General Hospital',
    institutionUri: 'http://example.org/institution/1',
    totalRecords: 35,
    completed: 25,
    rejected: 4,
    open: 6,
    qEval: 280,
    qInfo: 210,
    aEval: 259,
    aInfo: 194,
    correct: 238,
    completionRate: 71.4,
    rejectionRate: 11.4,
  },
  {
    username: 'fblazek',
    fullName: 'Frank Blažek',
    institution: 'General Hospital',
    institutionUri: 'http://example.org/institution/1',
    totalRecords: 14,
    completed: 8,
    rejected: 3,
    open: 3,
    qEval: 112,
    qInfo: 84,
    aEval: 95,
    aInfo: 70,
    correct: 71,
    completionRate: 57.1,
    rejectionRate: 21.4,
  },
  {
    username: 'gkucera',
    fullName: 'Greta Kučera',
    institution: 'General Hospital',
    institutionUri: 'http://example.org/institution/1',
    totalRecords: 28,
    completed: 20,
    rejected: 3,
    open: 5,
    qEval: 224,
    qInfo: 168,
    aEval: 207,
    aInfo: 155,
    correct: 190,
    completionRate: 71.4,
    rejectionRate: 10.7,
  },
  {
    username: 'hjelinek',
    fullName: 'Hans Jelínek',
    institution: 'City Clinic',
    institutionUri: 'http://example.org/institution/2',
    totalRecords: 24,
    completed: 15,
    rejected: 5,
    open: 4,
    qEval: 192,
    qInfo: 144,
    aEval: 168,
    aInfo: 122,
    correct: 138,
    completionRate: 62.5,
    rejectionRate: 20.8,
  },
  {
    username: 'imarkova',
    fullName: 'Irena Marková',
    institution: 'City Clinic',
    institutionUri: 'http://example.org/institution/2',
    totalRecords: 18,
    completed: 12,
    rejected: 2,
    open: 4,
    qEval: 144,
    qInfo: 108,
    aEval: 130,
    aInfo: 95,
    correct: 114,
    completionRate: 66.7,
    rejectionRate: 11.1,
  },
  {
    username: 'jsimanek',
    fullName: 'Jan Šimánek',
    institution: 'City Clinic',
    institutionUri: 'http://example.org/institution/2',
    totalRecords: 33,
    completed: 21,
    rejected: 7,
    open: 5,
    qEval: 264,
    qInfo: 198,
    aEval: 235,
    aInfo: 173,
    correct: 176,
    completionRate: 63.6,
    rejectionRate: 21.2,
  },
  {
    username: 'kvesela',
    fullName: 'Klára Veselá',
    institution: 'City Clinic',
    institutionUri: 'http://example.org/institution/2',
    totalRecords: 21,
    completed: 16,
    rejected: 2,
    open: 3,
    qEval: 168,
    qInfo: 126,
    aEval: 155,
    aInfo: 114,
    correct: 143,
    completionRate: 76.2,
    rejectionRate: 9.5,
  },
  {
    username: 'lpospisil',
    fullName: 'Lukáš Pospíšil',
    institution: 'City Clinic',
    institutionUri: 'http://example.org/institution/2',
    totalRecords: 16,
    completed: 9,
    rejected: 4,
    open: 3,
    qEval: 128,
    qInfo: 96,
    aEval: 109,
    aInfo: 80,
    correct: 76,
    completionRate: 56.3,
    rejectionRate: 25.0,
  },
  {
    username: 'mnovakova',
    fullName: 'Marta Nováková',
    institution: 'City Clinic',
    institutionUri: 'http://example.org/institution/2',
    totalRecords: 29,
    completed: 20,
    rejected: 4,
    open: 5,
    qEval: 232,
    qInfo: 174,
    aEval: 213,
    aInfo: 158,
    correct: 195,
    completionRate: 69.0,
    rejectionRate: 13.8,
  },
  {
    username: 'nbenes',
    fullName: 'Norbert Beneš',
    institution: 'University Medical Center',
    institutionUri: 'http://example.org/institution/3',
    totalRecords: 26,
    completed: 18,
    rejected: 4,
    open: 4,
    qEval: 208,
    qInfo: 156,
    aEval: 190,
    aInfo: 140,
    correct: 174,
    completionRate: 69.2,
    rejectionRate: 15.4,
  },
  {
    username: 'ocervena',
    fullName: 'Olga Červená',
    institution: 'University Medical Center',
    institutionUri: 'http://example.org/institution/3',
    totalRecords: 20,
    completed: 15,
    rejected: 2,
    open: 3,
    qEval: 160,
    qInfo: 120,
    aEval: 148,
    aInfo: 109,
    correct: 137,
    completionRate: 75.0,
    rejectionRate: 10.0,
  },
  {
    username: 'pkratochvil',
    fullName: 'Pavel Kratochvíl',
    institution: 'University Medical Center',
    institutionUri: 'http://example.org/institution/3',
    totalRecords: 23,
    completed: 14,
    rejected: 5,
    open: 4,
    qEval: 184,
    qInfo: 138,
    aEval: 161,
    aInfo: 118,
    correct: 130,
    completionRate: 60.9,
    rejectionRate: 21.7,
  },
  {
    username: 'rkopecka',
    fullName: 'Renata Kopecká',
    institution: 'University Medical Center',
    institutionUri: 'http://example.org/institution/3',
    totalRecords: 17,
    completed: 12,
    rejected: 2,
    open: 3,
    qEval: 136,
    qInfo: 102,
    aEval: 124,
    aInfo: 92,
    correct: 115,
    completionRate: 70.6,
    rejectionRate: 11.8,
  },
  {
    username: 'svlcek',
    fullName: 'Stanislav Vlček',
    institution: 'University Medical Center',
    institutionUri: 'http://example.org/institution/3',
    totalRecords: 30,
    completed: 19,
    rejected: 6,
    open: 5,
    qEval: 240,
    qInfo: 180,
    aEval: 214,
    aInfo: 158,
    correct: 171,
    completionRate: 63.3,
    rejectionRate: 20.0,
  },
  {
    username: 'tblazkova',
    fullName: 'Tereza Blažková',
    institution: 'Regional Health Institute',
    institutionUri: 'http://example.org/institution/4',
    totalRecords: 15,
    completed: 8,
    rejected: 4,
    open: 3,
    qEval: 120,
    qInfo: 90,
    aEval: 101,
    aInfo: 74,
    correct: 72,
    completionRate: 53.3,
    rejectionRate: 26.7,
  },
  {
    username: 'umarek',
    fullName: 'Uwe Marek',
    institution: 'Regional Health Institute',
    institutionUri: 'http://example.org/institution/4',
    totalRecords: 12,
    completed: 7,
    rejected: 3,
    open: 2,
    qEval: 96,
    qInfo: 72,
    aEval: 83,
    aInfo: 61,
    correct: 60,
    completionRate: 58.3,
    rejectionRate: 25.0,
  },
  {
    username: 'vzemanova',
    fullName: 'Věra Zemanová',
    institution: 'Regional Health Institute',
    institutionUri: 'http://example.org/institution/4',
    totalRecords: 19,
    completed: 11,
    rejected: 4,
    open: 4,
    qEval: 152,
    qInfo: 114,
    aEval: 133,
    aInfo: 98,
    correct: 105,
    completionRate: 57.9,
    rejectionRate: 21.1,
  },
  {
    username: 'wshedy',
    fullName: 'Waldemar Šedý',
    institution: 'Regional Health Institute',
    institutionUri: 'http://example.org/institution/4',
    totalRecords: 10,
    completed: 5,
    rejected: 3,
    open: 2,
    qEval: 80,
    qInfo: 60,
    aEval: 66,
    aInfo: 48,
    correct: 45,
    completionRate: 50.0,
    rejectionRate: 30.0,
  },
  {
    username: 'xbartosova',
    fullName: 'Xenie Bartošová',
    institution: 'Regional Health Institute',
    institutionUri: 'http://example.org/institution/4',
    totalRecords: 13,
    completed: 8,
    rejected: 2,
    open: 3,
    qEval: 104,
    qInfo: 78,
    aEval: 91,
    aInfo: 67,
    correct: 78,
    completionRate: 61.5,
    rejectionRate: 15.4,
  },
  {
    username: 'ydusek',
    fullName: 'Yvonne Dušek',
    institution: 'Regional Health Institute',
    institutionUri: 'http://example.org/institution/4',
    totalRecords: 11,
    completed: 6,
    rejected: 3,
    open: 2,
    qEval: 88,
    qInfo: 66,
    aEval: 74,
    aInfo: 54,
    correct: 55,
    completionRate: 54.5,
    rejectionRate: 27.3,
  },
  {
    username: 'zfiala',
    fullName: 'Zdeněk Fiala',
    institution: 'Regional Health Institute',
    institutionUri: 'http://example.org/institution/4',
    totalRecords: 8,
    completed: 4,
    rejected: 2,
    open: 2,
    qEval: 64,
    qInfo: 48,
    aEval: 53,
    aInfo: 39,
    correct: 38,
    completionRate: 50.0,
    rejectionRate: 25.0,
  },
]

const toAuthorDto = (a: (typeof AUTHORS)[number]) => ({
  label: 'Authors across the system' as const,
  description: null,
  interval: INTERVAL,
  username: a.username,
  fullName: a.fullName,
  totalRecords: a.totalRecords,
  completionRate: a.completionRate,
  rejectionRate: a.rejectionRate,
  questions: { evaluable: a.qEval, informative: a.qInfo },
  answers: {
    evaluable: { answered: a.aEval, correct: a.correct },
    informative: { answered: a.aInfo },
  },
  byPhase: { open: a.open, completed: a.completed, rejected: a.rejected },
  periodFrom: '2024-01-01T00:00:00Z',
  periodTo: '2024-12-31T23:59:59Z',
  institutionName: a.institution,
  institutionUri: a.institutionUri,
})

const MOCK_AUTHORS = AUTHORS.map(toAuthorDto)

const MOCK_OVERVIEW = {
  label: 'Authors across the system' as const,
  description: null,
  interval: INTERVAL,
  totalAuthors: MOCK_AUTHORS.length,
  mostRecordsAuthorInfo: 'Elena Svoboda – 35 records',
  mostAnswersAuthorInfo: 'Elena Svoboda – 453 answers',
  bestCompletionRateInfo: 'Klára Veselá – 76.2%',
  mostRejectionRateInfo: 'Waldemar Šedý – 30.0%',
  bestAnswerCorrectnessInfo: 'Renata Kopecká – 92.7%',
}

// Raw record data — qEval+qInfo must sum to totalQuestions,
// aEval+aInfo must sum to totalAnswers.
const RAW_RECORDS = [
  {
    uri: 'http://example.org/record/r001',
    name: 'Novák Jan – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-01-12T08:30:00Z',
    qEval: 16,
    qInfo: 4,
    aEval: 16,
    aInfo: 4,
    correct: 14,
    authorFullName: 'Alice Novák',
    authorUsername: 'anovak',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r002',
    name: 'Svoboda Petr – propuštění',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Discharge form',
    dateCreated: '2024-01-18T10:15:00Z',
    qEval: 13,
    qInfo: 2,
    aEval: 13,
    aInfo: 2,
    correct: 12,
    authorFullName: 'Bob Procházka',
    authorUsername: 'bprochazka',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r003',
    name: null,
    phase: 'OPEN' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-01-25T14:00:00Z',
    qEval: 16,
    qInfo: 4,
    aEval: 0,
    aInfo: 11,
    correct: 0,
    authorFullName: 'Clara Dvořák',
    authorUsername: 'cdvorak',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r004',
    name: 'Horáček Jiří – kontrola',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Follow-up form',
    dateCreated: '2024-02-03T09:45:00Z',
    qEval: 8,
    qInfo: 2,
    aEval: 8,
    aInfo: 2,
    correct: 5,
    authorFullName: 'David Horáček',
    authorUsername: 'dhoracek',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r005',
    name: 'Procházková Eva – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-02-10T11:20:00Z',
    qEval: 17,
    qInfo: 3,
    aEval: 17,
    aInfo: 3,
    correct: 16,
    authorFullName: 'Elena Svoboda',
    authorUsername: 'esvoboda',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r006',
    name: null,
    phase: 'REJECTED' as const,
    formTemplateLabel: 'Emergency form',
    dateCreated: '2024-02-14T16:30:00Z',
    qEval: 10,
    qInfo: 2,
    aEval: 10,
    aInfo: 2,
    correct: 6,
    authorFullName: 'Frank Blažek',
    authorUsername: 'fblazek',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r007',
    name: 'Nováková Lucie – propuštění',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Discharge form',
    dateCreated: '2024-02-22T08:00:00Z',
    qEval: 12,
    qInfo: 3,
    aEval: 12,
    aInfo: 3,
    correct: 11,
    authorFullName: 'Greta Kučera',
    authorUsername: 'gkucera',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r008',
    name: null,
    phase: 'OPEN' as const,
    formTemplateLabel: 'Follow-up form',
    dateCreated: '2024-03-01T13:10:00Z',
    qEval: 8,
    qInfo: 2,
    aEval: 0,
    aInfo: 4,
    correct: 0,
    authorFullName: 'Alice Novák',
    authorUsername: 'anovak',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r009',
    name: 'Blažek Tomáš – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-03-08T09:30:00Z',
    qEval: 15,
    qInfo: 5,
    aEval: 15,
    aInfo: 4,
    correct: 13,
    authorFullName: 'Elena Svoboda',
    authorUsername: 'esvoboda',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r010',
    name: null,
    phase: 'REJECTED' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-03-15T15:45:00Z',
    qEval: 11,
    qInfo: 9,
    aEval: 11,
    aInfo: 3,
    correct: 4,
    authorFullName: 'David Horáček',
    authorUsername: 'dhoracek',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r011',
    name: 'Veselá Jana – kontrola',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Follow-up form',
    dateCreated: '2024-03-22T10:00:00Z',
    qEval: 9,
    qInfo: 1,
    aEval: 9,
    aInfo: 1,
    correct: 9,
    authorFullName: 'Greta Kučera',
    authorUsername: 'gkucera',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r012',
    name: 'Kratochvíl Karel – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-04-02T08:15:00Z',
    qEval: 16,
    qInfo: 4,
    aEval: 16,
    aInfo: 4,
    correct: 15,
    authorFullName: 'Clara Dvořák',
    authorUsername: 'cdvorak',
    institutionName: 'General Hospital',
  },
  {
    uri: 'http://example.org/record/r013',
    name: 'Jelínek Radek – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-01-15T09:00:00Z',
    qEval: 16,
    qInfo: 4,
    aEval: 16,
    aInfo: 4,
    correct: 15,
    authorFullName: 'Hans Jelínek',
    authorUsername: 'hjelinek',
    institutionName: 'City Clinic',
  },
  {
    uri: 'http://example.org/record/r014',
    name: null,
    phase: 'OPEN' as const,
    formTemplateLabel: 'Follow-up form',
    dateCreated: '2024-02-05T11:30:00Z',
    qEval: 8,
    qInfo: 2,
    aEval: 0,
    aInfo: 6,
    correct: 0,
    authorFullName: 'Irena Marková',
    authorUsername: 'imarkova',
    institutionName: 'City Clinic',
  },
  {
    uri: 'http://example.org/record/r015',
    name: 'Šimánek Ondřej – propuštění',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Discharge form',
    dateCreated: '2024-02-19T14:20:00Z',
    qEval: 13,
    qInfo: 2,
    aEval: 13,
    aInfo: 2,
    correct: 10,
    authorFullName: 'Jan Šimánek',
    authorUsername: 'jsimanek',
    institutionName: 'City Clinic',
  },
  {
    uri: 'http://example.org/record/r016',
    name: 'Veselá Monika – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-03-04T08:45:00Z',
    qEval: 17,
    qInfo: 3,
    aEval: 17,
    aInfo: 3,
    correct: 16,
    authorFullName: 'Klára Veselá',
    authorUsername: 'kvesela',
    institutionName: 'City Clinic',
  },
  {
    uri: 'http://example.org/record/r017',
    name: null,
    phase: 'REJECTED' as const,
    formTemplateLabel: 'Emergency form',
    dateCreated: '2024-03-18T17:00:00Z',
    qEval: 10,
    qInfo: 2,
    aEval: 10,
    aInfo: 2,
    correct: 5,
    authorFullName: 'Lukáš Pospíšil',
    authorUsername: 'lpospisil',
    institutionName: 'City Clinic',
  },
  {
    uri: 'http://example.org/record/r018',
    name: 'Nováková Alžběta – kontrola',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Follow-up form',
    dateCreated: '2024-04-01T10:30:00Z',
    qEval: 9,
    qInfo: 1,
    aEval: 9,
    aInfo: 1,
    correct: 8,
    authorFullName: 'Marta Nováková',
    authorUsername: 'mnovakova',
    institutionName: 'City Clinic',
  },
  {
    uri: 'http://example.org/record/r019',
    name: 'Beneš Miroslav – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-01-22T09:15:00Z',
    qEval: 15,
    qInfo: 5,
    aEval: 15,
    aInfo: 4,
    correct: 14,
    authorFullName: 'Norbert Beneš',
    authorUsername: 'nbenes',
    institutionName: 'University Medical Center',
  },
  {
    uri: 'http://example.org/record/r020',
    name: null,
    phase: 'OPEN' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-02-08T13:00:00Z',
    qEval: 16,
    qInfo: 4,
    aEval: 0,
    aInfo: 8,
    correct: 0,
    authorFullName: 'Olga Červená',
    authorUsername: 'ocervena',
    institutionName: 'University Medical Center',
  },
  {
    uri: 'http://example.org/record/r021',
    name: 'Kratochvíl Zdeněk – propuštění',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Discharge form',
    dateCreated: '2024-02-26T11:45:00Z',
    qEval: 12,
    qInfo: 3,
    aEval: 12,
    aInfo: 3,
    correct: 9,
    authorFullName: 'Pavel Kratochvíl',
    authorUsername: 'pkratochvil',
    institutionName: 'University Medical Center',
  },
  {
    uri: 'http://example.org/record/r022',
    name: 'Kopecká Renata – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-03-12T08:00:00Z',
    qEval: 17,
    qInfo: 3,
    aEval: 17,
    aInfo: 3,
    correct: 16,
    authorFullName: 'Renata Kopecká',
    authorUsername: 'rkopecka',
    institutionName: 'University Medical Center',
  },
  {
    uri: 'http://example.org/record/r023',
    name: null,
    phase: 'REJECTED' as const,
    formTemplateLabel: 'Emergency form',
    dateCreated: '2024-03-28T16:20:00Z',
    qEval: 9,
    qInfo: 3,
    aEval: 9,
    aInfo: 2,
    correct: 4,
    authorFullName: 'Stanislav Vlček',
    authorUsername: 'svlcek',
    institutionName: 'University Medical Center',
  },
  {
    uri: 'http://example.org/record/r024',
    name: 'Blažková Jana – kontrola',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Follow-up form',
    dateCreated: '2024-01-30T10:00:00Z',
    qEval: 8,
    qInfo: 2,
    aEval: 8,
    aInfo: 2,
    correct: 6,
    authorFullName: 'Tereza Blažková',
    authorUsername: 'tblazkova',
    institutionName: 'Regional Health Institute',
  },
  {
    uri: 'http://example.org/record/r025',
    name: null,
    phase: 'OPEN' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-02-15T14:30:00Z',
    qEval: 16,
    qInfo: 4,
    aEval: 0,
    aInfo: 7,
    correct: 0,
    authorFullName: 'Uwe Marek',
    authorUsername: 'umarek',
    institutionName: 'Regional Health Institute',
  },
  {
    uri: 'http://example.org/record/r026',
    name: 'Zemanová Věra – příjem',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-03-05T09:30:00Z',
    qEval: 14,
    qInfo: 6,
    aEval: 14,
    aInfo: 4,
    correct: 11,
    authorFullName: 'Věra Zemanová',
    authorUsername: 'vzemanova',
    institutionName: 'Regional Health Institute',
  },
  {
    uri: 'http://example.org/record/r027',
    name: null,
    phase: 'REJECTED' as const,
    formTemplateLabel: 'Discharge form',
    dateCreated: '2024-03-20T15:00:00Z',
    qEval: 12,
    qInfo: 3,
    aEval: 12,
    aInfo: 3,
    correct: 5,
    authorFullName: 'Waldemar Šedý',
    authorUsername: 'wshedy',
    institutionName: 'Regional Health Institute',
  },
  {
    uri: 'http://example.org/record/r028',
    name: 'Bartošová Zuzana – kontrola',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Follow-up form',
    dateCreated: '2024-04-05T11:00:00Z',
    qEval: 9,
    qInfo: 1,
    aEval: 9,
    aInfo: 1,
    correct: 8,
    authorFullName: 'Xenie Bartošová',
    authorUsername: 'xbartosova',
    institutionName: 'Regional Health Institute',
  },
]

type RawRecordBase = {
  uri: string
  name: string | null
  phase: RecordPhase
  formTemplateLabel: string
  dateCreated: string
  qEval: number
  qInfo: number
  aEval: number
  aInfo: number
  correct: number
}

const toRecordDto = (r: RawRecordBase) => ({
  uri: r.uri,
  name: r.name,
  phase: r.phase,
  formTemplateLabel: r.formTemplateLabel,
  dateCreated: r.dateCreated,
  questions: { evaluable: r.qEval, informative: r.qInfo },
  answers: {
    evaluable: { answered: r.aEval, correct: r.correct },
    informative: { answered: r.aInfo },
  },
})

const INSTITUTION_RAW = RAW_RECORDS.filter((r) => r.institutionName === 'General Hospital')

const PERSONAL_RECORDS = [
  {
    uri: 'http://example.org/record/af3d9',
    name: 'Jan Novák intake',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-02-08T09:14:00Z',
    qEval: 16,
    qInfo: 4,
    aEval: 16,
    aInfo: 4,
    correct: 14,
  },
  {
    uri: 'http://example.org/record/d554a',
    name: 'Svoboda follow-up',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Follow-up form',
    dateCreated: '2024-04-18T14:30:00Z',
    qEval: 8,
    qInfo: 2,
    aEval: 8,
    aInfo: 2,
    correct: 8,
  },
  {
    uri: 'http://example.org/record/k890h',
    name: 'Horáček discharge',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Discharge form',
    dateCreated: '2024-10-05T11:50:00Z',
    qEval: 14,
    qInfo: 1,
    aEval: 14,
    aInfo: 1,
    correct: 13,
  },
  {
    uri: 'http://example.org/record/b12cc',
    name: 'Novák discharge',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Discharge form',
    dateCreated: '2024-03-15T11:02:00Z',
    qEval: 12,
    qInfo: 3,
    aEval: 12,
    aInfo: 3,
    correct: 11,
  },
  {
    uri: 'http://example.org/record/f230d',
    name: 'Procházka discharge',
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Discharge form',
    dateCreated: '2024-05-27T16:10:00Z',
    qEval: 13,
    qInfo: 2,
    aEval: 13,
    aInfo: 2,
    correct: 12,
  },
  {
    uri: 'http://example.org/record/c887e',
    name: null,
    phase: 'REJECTED' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-04-01T08:45:00Z',
    qEval: 16,
    qInfo: 4,
    aEval: 10,
    aInfo: 4,
    correct: 6,
  },
  {
    uri: 'http://example.org/record/j321g',
    name: null,
    phase: 'REJECTED' as const,
    formTemplateLabel: 'Emergency form',
    dateCreated: '2024-09-11T15:25:00Z',
    qEval: 11,
    qInfo: 1,
    aEval: 11,
    aInfo: 1,
    correct: 7,
  },
  {
    uri: 'http://example.org/record/e991b',
    name: null,
    phase: 'OPEN' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-05-03T10:20:00Z',
    qEval: 16,
    qInfo: 4,
    aEval: 0,
    aInfo: 9,
    correct: 0,
  },
  {
    uri: 'http://example.org/record/h102c',
    name: 'Dvořák check-in',
    phase: 'OPEN' as const,
    formTemplateLabel: 'Follow-up form',
    dateCreated: '2024-07-09T13:40:00Z',
    qEval: 8,
    qInfo: 2,
    aEval: 0,
    aInfo: 4,
    correct: 0,
  },
  {
    uri: 'http://example.org/record/l567i',
    name: null,
    phase: 'OPEN' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-11-18T08:30:00Z',
    qEval: 16,
    qInfo: 4,
    aEval: 0,
    aInfo: 6,
    correct: 0,
  },
  {
    uri: 'http://example.org/record/g774f',
    name: null,
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Emergency form',
    dateCreated: '2024-06-14T07:55:00Z',
    qEval: 10,
    qInfo: 2,
    aEval: 10,
    aInfo: 2,
    correct: 9,
  },
  {
    uri: 'http://example.org/record/i456e',
    name: null,
    phase: 'COMPLETED' as const,
    formTemplateLabel: 'Admission form',
    dateCreated: '2024-08-22T09:00:00Z',
    qEval: 17,
    qInfo: 3,
    aEval: 17,
    aInfo: 3,
    correct: 15,
  },
]

export const mockStatisticsProvider: StatisticsProvider = {
  async getAllAuthorsOverview(_interval: StatisticsInterval) {
    return { ...MOCK_OVERVIEW, label: 'Authors across the system' as const }
  },

  async getAllAuthors(_interval: StatisticsInterval) {
    return {
      label: 'Authors across the system' as const,
      description: null,
      interval: INTERVAL,
      authors: MOCK_AUTHORS,
      overview: MOCK_OVERVIEW,
    }
  },

  async getInstitutionAuthorsOverview(_interval: StatisticsInterval) {
    return { ...MOCK_OVERVIEW, label: 'Authors in your institution' as const }
  },

  async getInstitutionAuthors(_interval: StatisticsInterval) {
    const authors = MOCK_AUTHORS.filter((a) => a.institutionName === 'General Hospital')
    return {
      label: 'Authors in your institution' as const,
      description: null,
      interval: INTERVAL,
      authors,
      overview: {
        ...MOCK_OVERVIEW,
        label: 'Authors in your institution' as const,
        totalAuthors: authors.length,
      },
    }
  },

  async getAuthorByUsername(username: string, _interval: StatisticsInterval) {
    return {
      label: 'Personal statistics' as const,
      description: null,
      interval: INTERVAL,
      username,
      fullName: 'Demo User',
      totalRecords: 38,
      completionRate: 65.8,
      rejectionRate: 13.2,
      questions: { evaluable: 418, informative: 114 },
      answers: {
        evaluable: { answered: 418, correct: 374 },
        informative: { answered: 114 },
      },
      byPhase: { open: 8, completed: 25, rejected: 5 },
      periodFrom: '2024-02-01T00:00:00Z',
      periodTo: '2024-11-30T23:59:59Z',
      institutionName: 'General Hospital',
      institutionUri: 'http://example.org/institution/1',
    }
  },

  async getPersonalRecords(_interval: StatisticsInterval) {
    return {
      label: 'My records' as const,
      description: null,
      interval: INTERVAL,
      total: PERSONAL_RECORDS.length,
      records: PERSONAL_RECORDS.map(toRecordDto),
      phaseDistribution: {
        interval: INTERVAL,
        total: PERSONAL_RECORDS.length,
        distribution: [
          { phase: 'OPEN' as const, count: 3, percentage: 25.0 },
          { phase: 'COMPLETED' as const, count: 7, percentage: 58.3 },
          { phase: 'REJECTED' as const, count: 2, percentage: 16.7 },
        ],
      },
      formTemplateUsage: {
        label: 'My records' as const,
        description: null,
        interval: INTERVAL,
        total: PERSONAL_RECORDS.length,
        templates: [
          {
            templateUri: 'http://example.org/form/admission',
            templateLabel: 'Admission form',
            count: 5,
            percentage: 41.7,
          },
          {
            templateUri: 'http://example.org/form/discharge',
            templateLabel: 'Discharge form',
            count: 3,
            percentage: 25.0,
          },
          {
            templateUri: 'http://example.org/form/followup',
            templateLabel: 'Follow-up form',
            count: 2,
            percentage: 16.7,
          },
          {
            templateUri: 'http://example.org/form/emergency',
            templateLabel: 'Emergency form',
            count: 2,
            percentage: 16.7,
          },
        ],
      },
    }
  },

  async getInstitutionRecords(_interval: StatisticsInterval) {
    const records = INSTITUTION_RAW.map((r) => ({
      ...toRecordDto(r),
      institutionName: r.institutionName,
      authorUsername: r.authorUsername,
    }))
    return {
      label: 'Records in your institution' as const,
      description: null,
      interval: INTERVAL,
      total: records.length,
      records,
      phaseDistribution: {
        interval: INTERVAL,
        total: records.length,
        distribution: [
          { phase: 'OPEN' as const, count: 2, percentage: 16.7 },
          { phase: 'COMPLETED' as const, count: 8, percentage: 66.7 },
          { phase: 'REJECTED' as const, count: 2, percentage: 16.7 },
        ],
      },
      formTemplateUsage: {
        label: 'Records in your institution' as const,
        description: null,
        interval: INTERVAL,
        total: records.length,
        templates: [
          {
            templateUri: 'http://example.org/form/admission',
            templateLabel: 'Admission form',
            count: 5,
            percentage: 41.7,
          },
          {
            templateUri: 'http://example.org/form/discharge',
            templateLabel: 'Discharge form',
            count: 3,
            percentage: 25.0,
          },
          {
            templateUri: 'http://example.org/form/followup',
            templateLabel: 'Follow-up form',
            count: 3,
            percentage: 25.0,
          },
          {
            templateUri: 'http://example.org/form/emergency',
            templateLabel: 'Emergency form',
            count: 1,
            percentage: 8.3,
          },
        ],
      },
    }
  },

  async getAllRecords(_interval: StatisticsInterval) {
    const records = RAW_RECORDS.map((r) => ({
      ...toRecordDto(r),
      institutionName: r.institutionName,
      authorFullName: r.authorFullName,
      authorUsername: r.authorUsername,
    }))
    return {
      label: 'All records in the system' as const,
      description: null,
      interval: INTERVAL,
      total: records.length,
      records,
      phaseDistribution: {
        interval: INTERVAL,
        total: records.length,
        distribution: [
          { phase: 'OPEN' as const, count: 6, percentage: 21.4 },
          { phase: 'COMPLETED' as const, count: 18, percentage: 64.3 },
          { phase: 'REJECTED' as const, count: 4, percentage: 14.3 },
        ],
      },
      formTemplateUsage: {
        label: 'All records in the system' as const,
        description: null,
        interval: INTERVAL,
        total: records.length,
        templates: [
          {
            templateUri: 'http://example.org/form/admission',
            templateLabel: 'Admission form',
            count: 12,
            percentage: 42.9,
          },
          {
            templateUri: 'http://example.org/form/discharge',
            templateLabel: 'Discharge form',
            count: 6,
            percentage: 21.4,
          },
          {
            templateUri: 'http://example.org/form/followup',
            templateLabel: 'Follow-up form',
            count: 6,
            percentage: 21.4,
          },
          {
            templateUri: 'http://example.org/form/emergency',
            templateLabel: 'Emergency form',
            count: 4,
            percentage: 14.3,
          },
        ],
      },
    }
  },

  async getAllInstitutions(_interval: StatisticsInterval) {
    return {
      label: 'Institutions across the system' as const,
      description: null,
      interval: INTERVAL,
      totalInstitutions: 4,
      mostRecordsInstitutionInfo: 'General Hospital – 89 records',
      mostAnswersInstitutionInfo: 'General Hospital – 1 240 answers',
      bestCompletionRateInstitutionInfo: 'General Hospital – 68.5%',
      mostRejectionRateInstitutionInfo: 'Regional Health Institute – 18.8%',
      bestAnswerCorrectnessInstitutionInfo: 'University Medical Center – 91.3%',
      institutions: [
        {
          uri: 'http://example.org/institution/1',
          name: 'General Hospital',
          totalRecords: 89,
          authorCount: 7,
          completionRate: 68.5,
          rejectionRate: 11.2,
          questions: { evaluable: 1240, informative: 340 },
          answers: { evaluable: { answered: 980, correct: 893 }, informative: { answered: 260 } },
        },
        {
          uri: 'http://example.org/institution/2',
          name: 'City Clinic',
          totalRecords: 72,
          authorCount: 6,
          completionRate: 58.3,
          rejectionRate: 16.7,
          questions: { evaluable: 1050, informative: 290 },
          answers: { evaluable: { answered: 820, correct: 714 }, informative: { answered: 140 } },
        },
        {
          uri: 'http://example.org/institution/3',
          name: 'University Medical Center',
          totalRecords: 54,
          authorCount: 5,
          completionRate: 64.8,
          rejectionRate: 13.0,
          questions: { evaluable: 810, informative: 220 },
          answers: { evaluable: { answered: 640, correct: 584 }, informative: { answered: 110 } },
        },
        {
          uri: 'http://example.org/institution/4',
          name: 'Regional Health Institute',
          totalRecords: 32,
          authorCount: 5,
          completionRate: 53.1,
          rejectionRate: 18.8,
          questions: { evaluable: 480, informative: 130 },
          answers: { evaluable: { answered: 380, correct: 318 }, informative: { answered: 50 } },
        },
      ],
    }
  },

  async getPermissions() {
    return {
      canReadAllRecords: true,
      canReadOrgRecords: true,
      canReadAllUsers: true,
      canReadOrgUsers: true,
      canReadAllOrganizations: true,
      canReadOrganization: true,
      canReadStatistics: true,
    }
  },
}
